swagger: '2.0'
host: jugadores.com
basePath: /Jugadores
produces:
  - aplication/json
info:
  version: 1.0.0
  title: Gestor Jugadores 
  description: Gestor Jugadores
  contact:
    name: Joaquín Moreno Sánchez
    email: jmorsan426@g.educaand.es
    url: https://github.com/jmorsan/
schemes:
  - http
  - https
paths:
  /Jugador/Acciones:
    post:
      operationId: crarJugador
      description: crea un Jugador
      consumes:
        - aplication/json
      parameters:
        - name: jugadorData
          in: body
          required: true
          schema:
            $ref: '#/definitions/Jugador'
      responses:
        204:
          description: OK

        404:
          description: Jugador no encontrado
          schema:
            $ref: '#/definitions/JugadorException'
        
        505:
          description: Server error
          schema:
            $ref: '#/definitions/JugadorException'
  
    put:
      operationId: modificarJugador
      description: modifica un Jugador
      consumes:
        - aplication/json
      parameters:
        - name: jugadorData
          in: body
          required: true
          schema:
            $ref: '#/definitions/Jugador'
      responses:
        204:
          description: OK
          
        404:
          description: Jugador no encontrado
          schema:
            $ref: '#/definitions/JugadorException'
        
        505:
          description: Server error
          schema:
            $ref: '#/definitions/JugadorException'
  
  /Jugador/Acciones/{numeroDorsal}:
    get:
      operationId: buscarJugador
      description: crea un Jugador
      consumes:
        - aplication/json
      parameters:
        - name: numeroDorsal
          in: path
          required: true
          type: integer
          format: int32
      responses:
        204:
          description: OK
          
        404:
          description: Jugador no encontrado
          schema:
            $ref: '#/definitions/JugadorException'
        
        505:
          description: Server error
          schema:
            $ref: '#/definitions/JugadorException'
    delete:
      operationId: borrarJugador
      description: borra un Jugador
      consumes:
        - aplication/json
      parameters:
        - name: numeroDorsal
          in: path
          required: true
          type: integer
          format: int32
      responses:
        204:
          description: OK
          
        404:
          description: Jugador no encontrado
          schema:
            $ref: '#/definitions/JugadorException'
        
        505:
          description: Server error
          schema:
            $ref: '#/definitions/JugadorException'
  /lista:
    get:
        operationId: listaJugadores
        description: crea un Jugador
        consumes:
          - aplication/json
        responses:
          200:
            description: Lista de jugadores
            schema:
              type: array
              items: 
                $ref: '#/definitions/Jugador'
          404:
            description: Lista no encontrada
            schema:
              $ref: '#/definitions/JugadorException'

    
definitions:
  Jugador:
    type: object
    description: esto es un jugador
    properties:
      nombre:
        type: string
      dorsal:
        type: integer
        format: int32
      goles:
        type: integer
        format: int32
      tarjetas:
        type: integer
        format: int32
            
  JugadorException:
    type: object
    properties:
      errorId:
        type: string
        description: This is the error id
      mensaje:
        type: string
        description: This is the mensaje of error
              
